code/django_blog/authentication/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import authentication.views as authentication

app_name = 'authentication'

urlpatterns = [
    path('register/', authentication.UserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', authentication.UsersList.as_view(), name='users-index'),
    path('users/<int:pk>/', authentication.UserDetailView.as_view(), name='user-detail')
]

code/django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

import main

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('authentication/', include('authentication.urls', namespace='authentication')),

    path('admin/', admin.site.urls),
]

code/django_blog/main/urls.py
from django.urls import path

import main.views as main

app_name = 'main'

urlpatterns = [
    path('', main.index, name='index'),
    path('posts/', main.PostsList.as_view(), name='posts-index'),
    path('posts/<int:pk>/', main.PostDetailView.as_view(), name='post-detail'),
]

code/django_blog/authentication/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models


class User(AbstractUser):
    REQUIRED_FIELDS = ['email', 'password']
    email = models.EmailField('email address', unique=True, null=False)
    birth_date = models.DateField(null=True, blank=True)
    username = models.CharField(max_length=60, null=False, unique=True)
    first_name = models.CharField(max_length=60,  blank=True)
    last_name = models.CharField(max_length=60, blank=True)


    def __str__(self):
        return self.username

code/django_blog/main/models.py
from django.db import models

from authentication.models import User


class Post(models.Model):
    title = models.CharField(max_length=200, null=False)
    body = models.TextField()
    created_at = models.DateTimeField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

code/django_blog/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm

from authentication.models import User


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('first_name',
                  'last_name',
                  'birth_date',
                  'email',
                  'username',
                  'password1',
                  'password2')

code/django_blog/authentication/views.py
from django.views.generic import CreateView, DetailView, ListView

from authentication.forms import UserCreateForm
from authentication.models import User


class UsersList(ListView):
    model = User
    # context_object_name = 'animals'
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["page_title"] = "Users List"
        return context


class UserCreateView(CreateView):
    model = User
    success_url = '/'
    form_class = UserCreateForm



    def form_valid(self, form):
        form.instance.is_superuser = 1
        return super().form_valid(form)





class UserDetailView(DetailView):
    model = User

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["page_title"] = f"User name: {self.get_object().username}"
        return context

code/django_blog/main/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from main.models import Post



def index(request):
    return render(request, 'main/index.html')


class PostsList(ListView):
    model = Post
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["page_title"] = "Posts List"
        return context


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["page_title"] = f"Post: {self.get_object().title}"
        return context

code/django_blog/authentication/templates/authentication/register_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

code/django_blog/authentication/templates/authentication/user_detail.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}
{% block main %}
    <h2><span class="name">{{ object.first_name }}</span> <span class="surname">{{ object.last_name }}</span></h2>
    <p>First name: {{ object.first_name }}</p>
    <p>Last name: {{ object.last_name }}</p>
    <p>Username: {{ object.username }}</p>
    <p>Email: {{ object.email }}</p>
    <p>Birthdate: {{ object.birth_date }}</p>
    <div class="body">
        {{ object.body }}
    </div>
    <a href="{%  url 'authentication:users-index' %}">Back to list</a>
{% endblock %}

code/django_blog/authentication/templates/authentication/user_form.html
{% extends 'root.html' %}

{% block main %}
    <div class="user-creation-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="save">
        </form>
    </div>

{% endblock %}

code/django_blog/authentication/templates/authentication/user_list.html
{% extends 'root.html' %}
{% block title %}
    {{ page_title }}
{% endblock %}
{% block main %}
    <h2>Users</h2>
    <ol>
        {% for user in user_list %}
            <li><a href="{% url 'authentication:user-detail' user.pk %}">{{ user.username }}</a></li>
        {% endfor %}
    </ol>
    <a href="{%  url 'main:index' %}">Back to Main</a>
{% endblock %}

code/django_blog/main/templates/main/index.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}
{% block main %}
    <h2>Index page</h2>
    <a href="{%  url 'authentication:register' %}">Register User</a><br>
    <a href="{%  url 'authentication:login' %}">Login</a><br>
    <a href="{%  url 'main:posts-index' %}">Posts list</a><br>
    <a href="{%  url 'authentication:users-index' %}">Users list</a>
{% endblock %}

code/django_blog/main/templates/main/post_detail.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}
{% block main %}
    <h2>{{ object.title }}</h2>
    <div class="body">
        {{ object.body }}
    </div>
    <a href="{%  url 'posts:posts-index' %}">Back to list</a>
{% endblock %}

code/django_blog/main/templates/main/post_list.html
{% extends 'root.html' %}

{% block title %}
    {{ page_title }}
{% endblock %}
{% block main %}
    <h2>Posts</h2>
    <ol>
        {% for post in post_list %}
            <li><a href="{% url 'main:post-detail' post.pk %}">{{ post.title }}</a></li>
        {% endfor %}
    </ol>
    <a href="{%  url 'main:index' %}">Back to Main</a>

{% endblock %}

code/django_blog/main/templates/main/user_list.html
{% extends 'root.html' %}
{% block title %}
    {{ page_title }}
{% endblock %}
{% block main %}
    <h2>Users</h2>
    <ol>
        {% for user in user_list %}
            <li><a href="{% url 'main:user-detail' user.pk %}">{{ user.login }}</a></li>
        {% endfor %}
    </ol>
    <a href="{%  url 'main:index' %}">Back to Main</a>
{% endblock %}

code/django_blog/templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
            Otus Zoo
        {% endblock %}
    </title>


    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>

{% block main %}
{% endblock %}

<footer>
    Otus, 2023
</footer>
</body>
</html>